### PR TITLE
Search Box added in Navigation Bar

### PR DESCRIPTION
**Pull request by ranjankuldeep**
ISSUE #82 

## Kindly Review it. 
@roopeshsn 

Screenshot 2022-10-13 at 2 55 23 PM

Screenshot 2022-10-13 at 2 55 17 PM

Screenshot 2022-10-13 at 2 55 10 PM

Screenshot 2022-10-13 at 2 54 52 PM

### CODE REVIEW

**Comment by ranjankuldeep** [comment]
Screenshot 2022-10-13 at 7 53 37 PM
Screenshot 2022-10-13 at 7 50 50 PM
Screenshot 2022-10-13 at 7 50 44 PM

**Comment by roopeshsn** [comment]
> Attach screenshots when signed in as a admin

I asked you to add screenshots when signed in as an admin. Check the README for admin account credentials.

**Comment by ranjankuldeep** [comment]
Screenshot 2022-10-13 at 8 37 51 PM
Screenshot 2022-10-13 at 8 38 01 PM

Screenshot 2022-10-13 at 8 38 12 PM

Screenshot 2022-10-13 at 8 38 19 PM

**Comment by roopeshsn** [comment]
The carousel is misaligned and the navbar is looking great on mobile screens.

**Comment by ranjankuldeep** [comment]
I couldn't find the misalignment, Can you please share the screenshot?

**Comment by ranjankuldeep** [comment]
## Please review it.
@roopeshsn 

Screenshot 2022-10-14 at 11 04 02 AM

Screenshot 2022-10-14 at 11 04 49 AM

Screenshot 2022-10-14 at 11 05 24 AM

**Comment by ranjankuldeep** [comment]
Can you please reply.
@roopeshsn

**Comment by roopeshsn** [comment]
It would be great if the user and the admin dropdown is within the menu option.

**Comment by ranjankuldeep** [comment]
Can you elaborate a little more?
Where would the menu option be?

**Comment by roopeshsn** [comment]
> Can you elaborate a little more? Where would the menu option be?

I am talking about mobile screens. That hamburger is the menu option.

**Comment by ranjankuldeep** [comment]
it's already there.
On clicking hamburger, the Search box and this admin user dropdown appear.

**Comment by roopeshsn** [comment]
The search box should not be within the menu.

**Comment by ranjankuldeep** [comment]
ok, i am making the changes.

**Comment by roopeshsn** [comment]
> ok, i am making the changes.

Go through the problem statement thoroughly before working on any issue.

**Pull request closed without merging**
