### PR TITLE
added start shopping message if no orders

### PR DESCRIPTION
**Pull request by ankitdas09**
Issue #50

### CODE REVIEW

**Review by roopeshsn — CHANGES_REQUESTED** [review]
Could you add the screenshots of the outcome both in mobile and desktop view?

**Comment by ankitdas09** [comment]
Heres desktop and mobile view
Screenshot 2022-10-04 at 12 26 26
Screenshot 2022-10-04 at 12 26 19

**Comment by roopeshsn** [comment]
Good work @ankitdas09

**Review by roopeshsn — COMMENTED** [review]
Good work @ankitdas09

**Pull request merged**
