### PR TITLE
Reduce unused CSS

### LINKED ISSUE #3: Reduce unused CSS
Reduce unused rules from stylesheets and defer CSS not used for above-the-fold content to decrease bytes consumed by network activity.

**React Bootstrap** is used for styling

### PR DESCRIPTION
**Pull request by jccdev45**
Resolves #3  (reduce unused CSS)

- Added config for PurgeCSS as per [this article](https://blog.logrocket.com/purgecss-remove-unused-css-code/) and [official PurgeCSS docs](https://purgecss.com/guides/react.html#eject-create-react-app):
  1. In `client` directory, run `npm i --save-dev @fullhuman/postcss-purgecss glob-all purgecss-webpack-plugin`
  2. In `package.json`, add to the `scripts` section `"postbuild": "purgecss --css build/static/css/*.css --content build/index.html build/static/js/*.js --output build/static/css"`
  3. Run `npm run eject`
  4. In `config/webpack.conf.js`, add to imports section:
    ```js
    // import PurgeCSS webpack plugin and glob-all
    const PurgecssPlugin = require('purgecss-webpack-plugin')
    const glob = require('glob-all')
    ```
  5. In the same file, directly above `new ManifestPlugin(...)`, add:
    ```js
    new PurgecssPlugin({
      paths: [paths.appHtml, ...glob.sync(`${paths.appSrc}/**/*`, { nodir: true })]
    }),
    ```
  6. To confirm, run `npm run build` and verify that the contents of `build/static/css` contain only the used CSS
- Build successfully tested
- Reduced size of CSS from ~10kb to ~4kb

### CODE REVIEW

**Comment by theroopesh** [comment]
Could you explain more about the configuration changes you have done?

**Comment by jccdev45** [comment]
Sure thing! I edited my comment with detailed steps of exactly what I did as per the articles.

**Comment by theroopesh** [comment]
No, I'm asking about the changes you have done in frontend/config

**Comment by jccdev45** [comment]
Ah I see, all of that is automatically added as part of the `eject` [process for Create React App](https://create-react-app.dev/docs/available-scripts/#npm-run-eject) needed to configure PurgeCSS. Sorry for the confusion. If you change your mind about ejecting, I can look into configuring Purge without it.

**Comment by theroopesh** [comment]
Ok. I feel that it will be better to not use the eject process to configure PurgeCSS

**Pull request closed without merging**
