### PR TITLE
first test on registering user

### PR DESCRIPTION
**Pull request by Felexonyango**
First test on user registration .

### CODE REVIEW

**Comment by Felexonyango** [comment]
test  one passed

**Comment by Felexonyango** [comment]
test one passed

**Comment by Felexonyango** [comment]
Yes,l'm making sure tests cases passes and l will more on this both
Frontend and backend

**Review by roopeshsn — CHANGES_REQUESTED** [review]
Look like the files are not formatted properly

**Comment by roopeshsn** [comment]
Wait, I'll soon add the prettier configuration file so that the formatting will be made easy and the code styling looks the same for all the contributors who are involved in this project. Meanwhile, you continue writing test cases.

**Comment by Felexonyango** [comment]
Alright , please add  so  that i can add on my end  too... Thank you

**Comment by Felexonyango** [comment]
solved kindly check at package-lock.json .I have updated new and i have completed  user route kindly confirm before further proceedings

**Comment by Felexonyango** [comment]
Here is screenshot of the tests
Screenshot from 2022-04-23 12-03-51

**Comment by Felexonyango** [comment]
Screenshot from 2022-04-23 13-20-41

**Comment by roopeshsn** [comment]
Looks like there is a conflict. Undo the package-lock.json commit. I have updated the package-lock.json file. So use the git pull command.

**Review by roopeshsn — APPROVED** [review]

**Review by roopeshsn — APPROVED** [review]

**Comment by Felexonyango** [comment]
Thank you for approving senior

**Comment by roopeshsn** [comment]
Good work @Felexonyango 

Always use the git pull command before working from your side. I'll add a prettier config file after that I'll ask you to format your code. You run the specified command and commit once.

**Comment by roopeshsn** [comment]
I would like you to be an active maintainer of this project. If you spot any bugs or performance-related issues please create an issue. So, that others can work on that. If you'd like to add any new feature please go ahead. Your contribution will highly benefit this project!

**Comment by roopeshsn** [comment]
I updated the package-lock.json file. Use git pull from your side

**Comment by Felexonyango** [comment]
Thank you for granting me the role senior .I  will  do  all

**Comment by Felexonyango** [comment]
Thank you  for granting me  a role . sure I will

**Comment by Felexonyango** [comment]
Thank you  for granting me  a role . sure I will

**Comment by roopeshsn** [comment]
That's good to hear. Cheers!

**Pull request merged**
