### PR TITLE
Search bar made responsive with respect to navbar

### PR DESCRIPTION
**Pull request by bhumika-1-3**
image
image

### CODE REVIEW

**Comment by roopeshsn** [comment]
In mobile view, there is no search bar!

**Comment by bhumika-1-3** [comment]
image

it appears when you click on the hamburger menu

**Comment by bhumika-1-3** [comment]
Do you want me to make it appear by default?

**Comment by roopeshsn** [comment]
> Do you want me to make it appear by default?

Yes

**Comment by bhumika-1-3** [comment]
image
By making it default the hamburger is not looking nice .

**Comment by roopeshsn** [comment]
You should take of all these?

**Comment by bhumika-1-3** [comment]
Sorry I didn't get you.

**Comment by bhumika-1-3** [comment]
image

something like this ?

**Pull request closed without merging**
