### PR TITLE
Dependent Dropdown & Form Validation

### PR DESCRIPTION
**Pull request by anujverma-eng**
Hi @roopeshsn, I have added the Dependent dropdown in ShippingScreen, and few
**Changes I Made**
- used Ternary in useState Hook, as the first time the User Came, he has nothing in Cart, so this can generate a React Error **A component is changing an uncontrolled input to be controlled. !! **
- Created an Array of Objects [ Locations ] as a separate module [ used in the ShippingScreen component].
- we will Iterate through the Locations array, depending on the hierarchy (1st Lvl - Countries > 2nd Lvl - State > 3rd Lvl Cities ).
- Once the User Selects the Countries, we are looping through the Locations array, and with the find method finding the Country and depends on the Country we assign the States to the State Dropdown, similarly for Cities depend on states.
- In OrderModel I've changed the Pincode type to STRING. (this results in MongoDB Error) 
 **['No write concern mode named 'majority`' found in replica set configuration' error](https://stackoverflow.com/questions/65305856/no-write-concern-mode-named-majority-found-in-replica-set-configuration-err)** 
and this Error I've solved in the **MONGODB_URI** in .env File [ **I removed the &w=majority part at the end of URI** ] 
[StackOverflow Answers ](https://stackoverflow.com/questions/65305856/no-write-concern-mode-named-majority-found-in-replica-set-configuration-err)
- I've added the comments in code, wherever I've changed something

**And Now,**
Our Users Can Select the Cities, depending on State, depending on Country
and the Pincode we will be using as STRING only.
image
image
image

**I hope this feature will enhance the UX a little more, although this is not so great feature, but will help to maintain the user experience more**

Also pls merge the Updated request (Deleted Temporary Code Runner)

### CODE REVIEW

**Review by roopeshsn — CHANGES_REQUESTED** [review]
Good work @anujverma-eng It seems you haven't formatted the code properly. Have you seen the prettier config file? There is a command to format files recursively. Take a look at the package.json file.

**Comment by anujverma-eng** [comment]
I've formatted the code accordingly in Both files

1. ShippingScreen.js
2. LocationsAvailable.js

**Comment by roopeshsn** [comment]
Everything works fine right from entering the address to placing the order.

**Comment by anujverma-eng** [comment]
ok Great, so can we Close this Pull request?
Requesting you to Merge this commit to the main code.
Thanks

**Pull request merged**
