### PR TITLE
spaces added between buttons

### PR DESCRIPTION
**Pull request by s-vamshi**
Updated UsersListScreen.js and ProductListScreen.js to add spaces between buttons

### CODE REVIEW

**Comment by roopeshsn** [comment]
I need to verify whether everything works fine. Could you add screenshots both in mobile and desktop view?

**Comment by s-vamshi** [comment]
Sure!

**Comment by s-vamshi** [comment]
**desktop view:**
tem
**mobile view**
tem2

**Comment by roopeshsn** [comment]
In mobile view, the buttons are placed vertically. Could you do anything about that?

**Comment by s-vamshi** [comment]
tem3
Is this ok?

**Comment by roopeshsn** [comment]
Would like to know how you achieved this?

**Comment by s-vamshi** [comment]
I have imported button group from react bootstrap and then used it to group buttons

**Review by roopeshsn — CHANGES_REQUESTED** [review]
But I am not able to see the changes you've done to avoid vertical stacking!

**Comment by s-vamshi** [comment]
@roopeshsn forgot to commit. Please check now

**Review by roopeshsn — APPROVED** [review]
Good work @s-vamshi

**Pull request merged**
