### PR TITLE
desired colour and font style added to logo

### PR DESCRIPTION
**Pull request by Utkarsh212**

### CODE REVIEW

**Comment by roopeshsn** [comment]
Could you add a screenshot of your work?

**Comment by Utkarsh212** [comment]
This is the snapshot of the logo
Screenshot 2022-10-04 191613

And this is of the whole page
Screenshot 2022-10-04 191557

**Comment by roopeshsn** [comment]
Why the page doesn't load for you?

**Comment by Utkarsh212** [comment]
As my job was only related to doing changes in frontend. That's why I made changes directly into the frontend part without using the backend. That's why the data is not fetched here.

**Review by roopeshsn — APPROVED** [review]
Good work @Utkarsh212

**Pull request merged**
