### PR TITLE
Fix/secure user info

### LINKED ISSUE #102: User info are saved in local storage which is vulnerable to user
The user information like email, password, token are saved in local storage which is vulnerable to user privacy. Come up with a solution to address this issue.

userinfo_local_freshbey

### PR DESCRIPTION
**Pull request by ozair-dev**
Storing jwt in cookie instead of local storage

Implementation:

1. User signs in/up and the browser gets a accessToken cookie assigned to it.
2. Then the app makes another GET request to "/api/users/profile" and receives user info as response

Pros:
1. User's sensitive info is now secure
2. No need to add Authorization header on requests anymore

Fixes #102

### CODE REVIEW

**Comment by roopeshsn** [comment]
Hi @ozair-dev Apologies for the delay. The registration and login process is working fine right?

**Comment by roopeshsn** [comment]
If every thing is fine, format the code using Prettier. We have a command for that to format recursively. Check the package.json file.

**Comment by ozair-dev** [comment]
Login/signup was working fine on my machine. I'd still encourage you to test the changes yourself.
And about prettier, I ran it and it completed but files are not modified. I guess the code is already correctly formatted.

**Comment by roopeshsn** [comment]
How I can test myself before the merge? Is there any way to do that?

**Comment by ozair-dev** [comment]
@roopeshsn yes you can do that. I haven't had to test a pull request before but it is definitely possible. You can google how to do it.

**Pull request merged**
