### PR TITLE
added sort functionality to search and category page

### LINKED ISSUE #104: Create a Sort functionality
**Is your feature request related to a problem? Please describe.**
Create a sort option so that users can sort the products from low to high or high to low by price.

**Describe the solution you'd like**
Here is the sort option in amazon.in

sort_feature_1

sort_feature_2

Implement the same functionality in Freshbey. As of now we only need "low to high" and "high to low" by price options in the sort dropdown.

**Describe alternatives you've considered**
_No response_

**Additional context**
_No response_

### PR DESCRIPTION
**Pull request by kanavmittal**
@roopeshsn
This commit resolves #104
Screenshot 2022-10-17 at 3 12 27 AM

### CODE REVIEW

**Comment by roopeshsn** [comment]
Hi, @kanavmittal Could you show the functionality through a screen recorded video?

**Comment by kanavmittal** [comment]
@roopeshsn sure

**Comment by kanavmittal** [comment]
https://user-images.githubusercontent.com/33971670/196223234-36899489-7f45-411f-b82e-7b6e62103f27.MP4

@roopeshsn for mobile view

**Comment by kanavmittal** [comment]
https://user-images.githubusercontent.com/33971670/196224060-bdba0433-e52d-44c1-a194-6affa88785a6.mov

@roopeshsn for desktop view

**Comment by roopeshsn** [comment]
> @roopeshsn anything needed?

Yeah

**Review by roopeshsn — CHANGES_REQUESTED** [review]
Kindly do the changes.

**Comment by roopeshsn** [comment]
Hey, @kanavmittal Are you not interested to get this PR merged?

**Pull request closed without merging**
