### PR TITLE
integrate PurgeCSS

### PR DESCRIPTION
**Pull request by alpavlove**
Resolves https://github.com/roopeshsn/freshbey/issues/3 (reduce unused CSS)

Added a run of PurgeCSS CLI as the `postbuild` script. This method doesn't require ejecting CRA or setting up Craco or similar tools. 

It has been tested successfully

Reduced size of CSS from ~172kb to ~25kb raw and ~29.5kb to ~6.6kb  gzip

### CODE REVIEW

**Comment by alpavlove** [comment]
There is an issue with npm. `package-lock.json` files are generated by a new version of node (16+), but the project requires 14. So `package-lock.json` has been regenerated by the 14 version

**Comment by roopeshsn** [comment]
Good work @alpavlove! Thanks for your efforts!

**Comment by roopeshsn** [comment]
I would like you to be an active maintainer of this project. If you spot any bugs or performance-related issues please create an issue. So, that others can work on that. If you'd like to add any new feature please go ahead. Your contribution will highly benefit this project!

**Comment by alpavlove** [comment]
Thanks for the invitation @roopeshsn. I will!

**Pull request merged**
